name: Create a release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create a release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true